# Generated by Django 3.0.14 on 2023-05-16 02:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gpa', models.DecimalField(decimal_places=1, max_digits=12, validators=[django.core.validators.MaxValueValidator(4)])),
                ('student_id', models.IntegerField(validators=[django.core.validators.MaxValueValidator(29999999)])),
                ('img', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('active', models.BooleanField(default=False)),
                ('NationalID', models.IntegerField()),
                ('date', models.DateField(verbose_name='')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('phonenum', models.DecimalField(decimal_places=0, max_digits=13)),
                ('department', models.CharField(choices=[('CS', 'CS'), ('IS', 'IS'), ('AI', 'AI'), ('DS', 'DS'), ('General', 'General')], default='General', max_length=10)),
                ('level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=1)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
