# Generated by Django 3.0.14 on 2023-05-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20230516_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(default='photos/male.png', null=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
