# Generated by Django 3.0.14 on 2023-05-16 02:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20230516_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(29999999)]),
        ),
    ]
